$ANSIBLE_VAULT;1.1;AES256
61646138313562663830303432326463363535636630613537333835623535306432613566383830
3262386133653235646539353461326163613635333132340a626264326637626637313962376533
66356438326330363763353266366430623064323264373230343962666564613133316262316331
6235363535623764610a376631363439626533633065343233616232303139326637346263393134
34653634356134616163623265633339313262346361653965393438663338636165303865366566
30366231316363666561313139303666373532613763353763663763356666653439363736383736
62393334626664613965616562393735366465636136623536383334643366646562636332313435
66386331333365646535393630353563343063303831613032333431376534373331346664396236
62353836346561633832373461393333346439653733623430633766386435373361663965383463
36616332653132623864313563333337333531353766373934396630336263653638343865336361
33373439346230313138313831336232353936376663303131343333313634663838373435346264
63386566303563336437666236386265653463363634343438316665353738386236386166396162
6666
