$ANSIBLE_VAULT;1.1;AES256
36393465646465383939666134393135663764636531313334383562386338656462333435353265
3538353839666363666533343036346134306562353866630a656236656363353430396561353862
34353964396133656462633866303430643030633131373737303338336237623866373731663765
3732363064343666610a323733346431353462306432646537306336383066313664666364373264
32373932386164643535653166316161616135326162363065313265396136356138316538643837
36653164326266613432646431643566383636336332376334376662323935643162396537373334
39303430346561653734336133613634333766613033646463616639376239336432636433313033
35663030313430393463316666373062336431383563326663383135653730326134306639626162
64663865353330316464666562656639333238316465313834316566396264303337396466646539
30653133393366666339613139666661313730633333313761663261656336626566636337633938
37356237343962313536303565323439393637643935376536616666363930366536656530353638
32313931396535373361383466623661653864303832353533333530393439613961636163623835
3161
